#!/usr/bin/env bash
brew install aom
brew install apr
brew install apr-util
brew install argon2
brew install autoconf
brew install bdw-gc
brew install brotli
brew install c-ares
brew install ca-certificates
brew install cairo
brew install certifi
brew install composer
brew install crystal
brew install curl
brew install fd
brew install fontconfig
brew install freetds
brew install freetype
brew install fribidi
brew install gd
brew install gettext
brew install gh
brew install ghostscript
brew install giflib
brew install glib
brew install glow
brew install gmp
brew install graphite2
brew install harfbuzz
brew install highway
brew install icu4c@76
brew install imagemagick
brew install imath
brew install jasper
brew install jbig2dec
brew install jpeg-turbo
brew install jpeg-xl
brew install jq
brew install krb5
brew install leptonica
brew install libarchive
brew install libavif
brew install libb2
brew install libde265
brew install libdeflate
brew install libevent
brew install libheif
brew install libidn
brew install libidn2
brew install liblinear
brew install liblqr
brew install libnghttp2
brew install libomp
brew install libpng
brew install libpq
brew install libraw
brew install libsodium
brew install libssh2
brew install libtiff
brew install libtommath
brew install libtool
brew install libunistring
brew install libuv
brew install libvmaf
brew install libx11
brew install libxau
brew install libxcb
brew install libxdmcp
brew install libxext
brew install libxrender
brew install libyaml
brew install libzip
brew install little-cms2
brew install llvm
brew install lua
brew install lynx
brew install lz4
brew install lzo
brew install m4
brew install marked
brew install mpdecimal
brew install ncurses
brew install net-snmp
brew install nim
brew install nmap
brew install node
brew install oniguruma
brew install openexr
brew install openjpeg
brew install openldap
brew install openssl@3
brew install pandoc
brew install pango
brew install pcre2
brew install php
brew install pixman
brew install pkgconf
brew install python-packaging
brew install python-tk@3.12
brew install python-tk@3.13
brew install python@3.12
brew install python@3.13
brew install readline
brew install rtmpdump
brew install shared-mime-info
brew install speedtest-cli
brew install sqlite
brew install tcl-tk
brew install tesseract
brew install tidy-html5
brew install tldr
brew install typescript
brew install typespeed
brew install unixodbc
brew install webp
brew install wget
brew install x265
brew install xorgproto
brew install xz
brew install yt-dlp
brew install z3
brew install zsh-autosuggestions
brew install zsh-syntax-highlighting
brew install zstd
brew install brave-browser
brew install chatgpt
brew install chromedriver
brew install firefox@developer-edition
brew install github
brew install google-chrome
brew install gstreamer-runtime
brew install microsoft-edge
brew install msty
brew install openemu
brew install pycharm-ce
brew install screenflow
brew install spotify
